# Generated by Django 2.0.7 on 2018-09-07 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('isbn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('booktitle', models.CharField(max_length=100)),
                ('bookAuthor', models.CharField(max_length=100)),
                ('yearOfPublication', models.CharField(max_length=50)),
                ('imageUrlS', models.CharField(max_length=250)),
                ('imageUrlM', models.CharField(max_length=250)),
                ('imageUrlL', models.CharField(max_length=250)),
                ('avgRating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('rateCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Books')),
            ],
        ),
    ]
