# Generated by Django 2.0.7 on 2018-09-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180907_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='shivam', max_length=100),
            preserve_default=False,
        ),
    ]
